[project]
name = "cs262_final_project"
version = "0.0.1"
description = "Distributed auction system (CS-2620 project)"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["system_main*"]
